version: '3.7'

services:
  starrocks:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        progress: plain

    container_name: "starrocks"
    hostname: "fe"
    ports:
      - "8030:8030"
      - "9030:9030"
      - "8040:8040"
    volumes:
      - ./starrocks/fe/meta:/opt/apache-doris/fe/meta
      - ./starrocks/fe/log:/data/deploy/starrocks/fe/log
      - ./starrocks/be/storage:/data/deploy/starrocks/be/storage
      - ./starrocks/be/log:/data/deploy/starrocks/be/log
      - ./initdb.d/:/docker-entrypoint-initdb.d/
