server:
  port: :4000
  version: 1.0
  jwtSecret: "38324-search-engine"

mysql:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: search_engine
  username: search_engine
  password: search_engine
  charset: utf8mb4

es:
  EsHost: 127.0.0.1
  EsPort: 9200
  EsIndex: mylog


redis:
  user_name: default
  address: 127.0.0.1:6379
  password:

etcd:
  address: 127.0.0.1:2379

services:
  gateway:
    name: gateway
    loadBalance: true
    addr:
      - 127.0.0.1:10001

  user:
    name: user
    loadBalance: false
    addr:
      - 127.0.0.1:10002

  favorite:
    name: favorite
    loadBalance: false
    addr:
      - 127.0.0.1:10003

  searchEngine:
    name: searchEngine
    loadBalance: false
    addr:
      - 127.0.0.1:10004

domain:
  user:
    name: user
  favorite:
    name: favorite
  searchEngine:
    name: searchEngine